name: uber
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.3+1
  google_fonts: ^1.0.0
  outline_material_icons: ^0.1.0
  url_launcher: ^5.0.3
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/logo.jpg
    - images/space.jpeg
    - images/spacex.jpg
    - images/uber.png
    - images/earth.jpg
    - images/mars.jpg
    - images/jupiter.jpeg
    - images/uranus.jpeg
    - images/rocket.jpg
    - images/spacepod.png
    - images/greenspace.jpeg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf

    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Regular.ttf

    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Light.ttf

